blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.sitemaps.views import sitemap
from blogs.sitemaps import PostSitemap

sitemaps = {
	'posts' :PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogs/',include('blogs.urls', namespace='blogs')),
	path('sitemap.xml',sitemap,{'sitemaps':sitemaps}, name='djnago.contrib.sitemaps.views.sitemap')    

]

blogs/urls.py
from django.urls import path
from .feeds import LatestPostsFeed

from . import views

app_name = 'blogs'

urlpatterns = [
	#post views
	path('',views.post_list, name="post_list"),
	path('tag/<slug:tag_slug>/',views.post_list, name="post_list_by_tag"),
	#path('',views.PostListView.as_view(), name ='post_list'),
	path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name="post_detail"),
	path('<int:post_id>/share/',views.post_share, name="post_share"),
	path('feed/',LatestPostsFeed(), name='post_feed'),
	path('search/',views.post_search,name="post_search"),
]

blogs/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.


class PublishedManager(models.Manager):
	def get_queryset(self):
		return super(PublishedManager,self).get_queryset()\
										   .filter(status='published')

class Post(models.Model):
	STATUS_CHOICES = (
			('draft', 'Draft'),
			('published', 'Published')
		)

	title = models.CharField(max_length=250)
	slug = models.SlugField(max_length=250,unique_for_date='publish')

	author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')


	body = models.TextField()
	publish = models.DateTimeField(default=timezone.now)
	created = models.DateTimeField(auto_now_add=True)
	updated= models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')


	class Meta:
		ordering = ('-publish',)


	def __str__(self):
		return self.title


	objects = models.Manager() # the default manager
	published = PublishedManager() # our custom manager


	def get_absolute_url(self):
		return reverse('blogs:post_detail',
			args=[self.publish.year,self.publish.month,self.publish.day,self.slug])


	tags = TaggableManager()

class Comment(models.Model):
	post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name="comments")
	name = models.CharField(max_length=80)
	email=models.EmailField()
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	active = models.BooleanField(default=True)

	class Meta:
		ordering = ('created',)

	def __str__(self):
		return 'Comment by {} on {} '.format(self.name,self.post)

blogs/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
	name = forms.CharField(max_length=25)
	email = forms.EmailField()
	to = forms.EmailField()
	comments = forms.CharField(required=False,widget=forms.Textarea)



class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('name','email','body')



class SearchForm(forms.Form):
	query=forms.CharField()
	

blogs/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post,Comment
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from django.conf import settings
from taggit.models import Tag
from django.db.models import Count

from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from .forms import EmailPostForm,CommentForm, SearchForm

def post_search(request):
	form = SearchForm()
	query = None
	results = []
	if 'query' in request.GET:
		form = SearchForm(request.GET)
		if form.is_valid():
			query = form.cleaned_data['query']
			#search_vector = SearchVector('title', 'body')
			search_vector = SearchVector('title',weight='A') + SearchVector('body', weight='B')
			search_query = SearchQuery(query)
			results = Post.objects.annotate(
					search=search_vector,
					rank = SearchRank(search_vector, search_query)
				).filter(rank__gte=0.3).order_by('-rank')
			#.filter(search=search_query).order_by('-rank')
			#results = Post.objects.annotate(search=SearchVector('title','body'),).filter(search=query)
			#results	=Post.objects.annotate(search=SearchVector('title',	'body'),).filter(search=query)		
	return render(request,'blogs/post/search.html',{'form':form,'query':query,'results':results})




def post_share(request, post_id):
	# retrieve post by id
	post = get_object_or_404(Post,id=post_id,status='published')
	sent = False

	if request.method == 'POST':
		# form was submitted
		form = EmailPostForm(request.POST)
		if form.is_valid():
			# Form fields passed validation
			cd = form.cleaned_data
			post_url = request.build_absolute_uri(post.get_absolute_url())
			subject = '{} ({}) recommends your reading "{}"'.format(cd['name'],cd['email'],post.title)
			message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title,post_url,cd['name'],cd['comments'])
			send_mail(subject, message, 'icjfuncion@gmail.com',[cd['to']],fail_silently=False)

			#testing
			# subject = 'Testing'
			# message = 'Testing body'
			# email_from = settings.EMAIL_HOST_USER
			# recipient_list = ['icjfuncion@gmail.com',]
			# send_mail(subject,message,email_from,recipient_list)
			sent =True
	else:
		form = EmailPostForm()

	
	return render(request,'blogs/post/share.html',{'post':post,'form':form,'sent':sent})


# class PostListView(ListView):
# 	queryset = Post.published.all()
# 	context_object_name = 'posts'
# 	paginate_by = 3
# 	template_name = 'blogs/post/list.html'

def post_list(request, tag_slug=None):
	object_list = Post.published.all()
	tag = None

	if tag_slug:
		tag = get_object_or_404(Tag, slug=tag_slug)
		object_list = object_list.filter(tags__in=[tag])


	paginator = Paginator(object_list, 3) #  posts in each page
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer deliver the first page
		posts = paginator.page(1)
	except EmptyPage:
		#if page is out of range deliver last page of results
		posts = paginator.page(paginator.num_pages)



	return render(request,'blogs/post/list.html',{'page':page,'posts':posts,'tag':tag})
# 	# posts = Post.published.all()
# 	# return render(request,'blogs/post/list.html',{'posts':posts})

def post_detail(request,year,month,day,post):
	post = get_object_or_404(Post, slug=post,status='published',publish__year=year,publish__month=month,publish__day=day)

	# List of active comments for this post
	comments = post.comments.filter(active=True)

	#initalize
	new_comment = None

	if request.method == 'POST':
		# a comment was posted
		comment_form = CommentForm(data=request.POST)
		if comment_form.is_valid():
			# Create comment object but don't save to database yet
			new_comment = comment_form.save(commit=False)
			# Assign the current post to the comment
			new_comment.post = post
			# Save the comment to the database
			new_comment.save()

	else:
		comment_form = CommentForm()


	# List of similar posts

	post_tags_ids = post.tags.values_list('id',flat=True)
	similar_posts = Post.published.filter(tags__in=post_tags_ids)\
								  .exclude(id=post.id)

	similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
							     .order_by('-same_tags','-publish')[:4]

	return render(request,'blogs/post/detail.html',{'post':post,'comments':comments,'comment_form':comment_form,'new_comment':new_comment,'similar_posts':similar_posts})


# # Create your views here.

# # filters in django
# # Post.objects.filter(publish__year=2015)
# # multiple filter filter by year published and the author
# # Post.objects.filter(publish__year=2017,author='ivan')
# # same as above but in chain 
# # Post.objects.filter(publish__year=2017) \
# # 			.filter(auther__username='admin')

# # publish__year and author__username are field lookups

# # Using exclude() # all but except for the this one
# # # get all post in 2017 excluding the title that starts with
# # Post.objects.filter(publish__year=2017) \
# # 			.exclude(title_startswith='why')

# # Using order_by()
# # Post.object.order_by('title')
# # # by default, it is in ascending order
# # #you can change it to descending order by putting a negative sign prefix
# # Post.object.order_by('-title')

# Deleting objects
# post = Post.objects.get(id=1)
# post.delete()
# # if you delete an object it will also delete any dependent relationships for foreignkey

blogs/templates/blogs/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>{% block title %} {% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'blogs:post_list'%}">Django Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
<!--       <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li> -->
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'blogs:post_search' %}" method="GET">
      <input class="form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<div class="container">

	<div class="row">
		<div class="col-md-8">
				{% block content %}
				{% endblock %}
		</div>


		<aside class="col-md-4 blog-sidebar">
			<div id="sidebar">
				<h2>My blog</h2>
				<p>This is my blog. I've written {% total_posts %} posts so far. </p>

				<p><a href="{% url 'blogs:post_feed' %}">Subscribe to my RSS feed</a></p>

				<h3>Latest posts</h3>
				{% show_latest_posts 3 %}

				<h3>Most commented posts</h3>
				{% get_most_commented_posts as most_commented_posts %}

				<ul>
					{% for post in most_commented_posts %}
					<li>
						<a href="{{post.get_absolute_url}}">{{ post.title}}</a>
					</li>
					{% endfor %}
				</ul>
			</div>
		</aside>
	</div>

</div>


<!-- <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script> -->


<script src="{% static 'js/jquery-3.4.1.min.js'%}"></script>
<script src="{% static 'js/popper.min.js'%}"></script>
<script src="{% static 'js/bootstrap.min.js'%}"></script>
</body>
</html>

blogs/templates/blogs/pagination.html
<nav aria-label="Page navigation example">
  <ul class="pagination">

  	{% if page.has_previous%}
    <li class="page-item"><a class="page-link" href="?page={{page.previous_page_number}}">Previous</a></li>
    {% else %}
    <li class="page-item disabled">
    	<a class="page-link" href="">Previous</a>
    </li>
    {% endif %}

    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
    {% else %}
    <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
    {% endif %}
    {% endfor %}

    {% if page.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">Next</a></li>
    {% else %}
    <li class="page-item disabled">
    	<a class="page-link" href="">Next</a>
    </li>
    {% endif %}
  </ul>
</nav>

blogs/templates/blogs/post/detail.html
{% extends "blogs/base.html" %}
{% load blog_tags %}
{% block title %} {{post.title}} {% endblock %}

{%block content %}

<h1>{{post.title}}</h1>
<p class="date">
	Published {{post.publish}} by {{post.author}}
</p>

<!--- before linebreaks--->
{{post.body|markdown}}

<p>
	<a href="{% url 'blogs:post_share' post.id %}">
		Share this post
	</a>
</p>



{% with comments.count as total_comments %}
<h2>
	{{ total_comments }} comment{{total_comments|pluralize}}
</h2>

{% endwith %}


{% for comment in comments %}

<div class="comment">
	<p class="info">
		comment {{forllop.counter }} by <b>{{comment.name}}</b> <i>{{comment.created}}</i>
	</p>
	{{ comment.body|linebreaks }}
</div>
{% empty %}
<p>There are no comments yet. </p>
{% endfor %}

<h2>Similar Post</h2>
{% for post in similar_posts %}
<p>
	<a href="{{ post.get_absolute_url }}">{{post.title}}</a>
</p>
{% empty %}

There are no similar posts yet.

{% endfor %}


{% if new_comment %}
<h2>Your comment has been added.</h2>


{% else %}
<h2>Add a new comment</h2>

{% load widget_tweaks %}


<form action="." method="POST">
	{% for field in comment_form %}
	<div class="form-group">
		{{field.errors}}
		{{field.label_tag}}
		{% render_field field class="form-control" %}
	</div>
	{% endfor %}
	{% csrf_token %}
	<p><input type="submit" class="btn btn-primary" name="Add comment"></p>
</form>
{% endif %}


{% endblock %}

blogs/templates/blogs/post/latest_posts.html
<ul>
	{% for post in latest_posts %}
	<li>
		<a href="{{post.get_absolute_url }}">{{ post.title }}</a>
	</li>
	{% endfor %}
</ul>

blogs/templates/blogs/post/list.html
{% extends "blogs/base.html" %}
{% load blog_tags %}
{% block title %}My Blog {% endblock %}

{% block content %}
<h1> My Blog</h1>
{% if tag %}
<h2>Posts tagged ith "{{ tag.name }}" </h2>
{% endif %}
{% for post in posts%}
<h2>
	<a href="{{post.get_absolute_url }}">
		{{post.title}}
	</a>
	<p class="tags">Tags: 
		{% for tag in post.tags.all %}
		<a href="{% url 'blogs:post_list_by_tag' tag.slug %}"> {{tag.name }}</a>
		{% if not forloop.last %}, {% endif %}
		{% endfor %}
	</p>
</h2>

<p class="date lead">
	Published {{ post.publish }} by {{ post.author }}
</p>

<!--- before truncatewords:30|linebreaks-->
{{ post.body|markdown|truncatewords_html:30 }}

{% endfor %}
<!-- previous value : posts
	page_obj because it is the object that the list view generic view passes
-->
{% include "blogs/pagination.html" with page=posts %}
{% endblock %}

blogs/templates/blogs/post/search.html
{% extends "blogs/base.html" %}
{% block title %}Search {% endblock %}

{% block content %}
{% if query %}
	<h1>Posts containing "{{ query }}"</h1>
	<h3>
		{% with results.count as total_results %}
			Found {{total_results}} result{{ total_results|pluralize }}
		{% endwith %}
	</h3>



	{% for post in results %}
		<h4><a href="{{ post.get_absolute_url }}">{{post.title}}</a></h4>
		{{ post.ody|truncatewords:5 }}

	{% empty %}
	<p>There are no results for your query</p>
	{% endfor  %}
	<p><a href="{% url 'blogs:post_search' %}">Search Again</a></p>

{% else %}

<h1>Search for posts</h1>
{% load widget_tweaks %}
<form action="." method="GET">

	{% for field in form %}
	<div class="form-group">
		{{field.errors}}
		{{field.label_tag}}
		{% render_field field class="form-control" %}
	</div>
	{% endfor %}

	<input type="submit" value="Search" class="btn btn-primary" name="">
</form>

{% endif %}
{% endblock %}

blogs/templates/blogs/post/share.html
{% extends "blogs/base.html "%}
{% block title %} Share a post {% endblock %}

{% block content %}
{% if sent %}

<h1>E-mail successfully sent</h1>
<p>
	"{{post.title}}" was successfully sent to {{form.cleaned_data.to}}.
</p>

{% else %}

<h1>Share "{{post.title}}" by email</h1>

{% load widget_tweaks %}

<form action="." method="POST">
	{% for field in form %}
	<div class="form-group">
		{{ field.errors }}
		{{field.label_tag }}
		{% render_field field class="form-control" %}
	</div>
	{% endfor %}
	
	{% csrf_token %}
	<input type="submit" class="btn btn-primary" value="Send e-mail" name="">
</form>

{% endif %}
{% endblock %}